# Generated by Django 5.1 on 2024-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("gender", models.CharField(max_length=20)),
                ("looking_for", models.CharField(max_length=20)),
                ("wedding_goal", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("partner_age_range", models.CharField(max_length=50)),
                ("partner_living_in_australia", models.CharField(max_length=20)),
                ("horoscope_match", models.CharField(max_length=50)),
                ("interests_and_hobbies", models.TextField()),
                ("qualification", models.CharField(max_length=50)),
                ("working_status", models.CharField(max_length=50)),
                ("income", models.CharField(max_length=50)),
                ("occupation", models.CharField(max_length=50)),
                ("marital_status", models.CharField(max_length=20)),
                ("smoking_habits", models.CharField(max_length=20)),
                ("drinking_habits", models.CharField(max_length=20)),
                ("eating_habits", models.CharField(max_length=20)),
                ("weight", models.IntegerField()),
                ("height", models.IntegerField()),
                ("caste", models.CharField(max_length=50)),
                ("community", models.CharField(max_length=50)),
                ("religion", models.CharField(max_length=50)),
            ],
        ),
    ]
