# Generated by Django 5.1 on 2024-08-17 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
